### ISSUE TITLE
IndexError: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by mackaiver** [cta-observatory/image-extractor#19]
I'm having trouble extracting images from simtel files. 
One of the files I'm looking at is
`proton_20deg_0deg_run20089___cta-prod3-merged_desert-2150m-Paranal-3HB89-NGFD.simtel.gz`

I get the following stacktrace:

```
(fact) [kbruegge@vollmond image-extractor]$ python image-extractor/image_extractor.py run_list.txt ./test.h5 
WARNING: AstropyDeprecationWarning: prefer the use of an EventSource or EventSourceFactory [__main__]
WARNING:astropy:AstropyDeprecationWarning: prefer the use of an EventSource or EventSourceFactory

gzip: stdout: Broken pipe
WARNING: AstropyDeprecationWarning: prefer the use of an EventSource or EventSourceFactory [__main__]
WARNING:astropy:AstropyDeprecationWarning: prefer the use of an EventSource or EventSourceFactory
WARNING:ctapipe.io.hessioeventsource.HESSIOEventSource:Only one pyhessio event_source allowed at a time. Previous hessio file will be closed.

gzip: stdout: Broken pipe
WARNING: AstropyDeprecationWarning: prefer the use of an EventSource or EventSourceFactory [__main__]
WARNING:astropy:AstropyDeprecationWarning: prefer the use of an EventSource or EventSourceFactory
WARNING:ctapipe.io.hessioeventsource.HESSIOEventSource:Only one pyhessio event_source allowed at a time. Previous hessio file will be closed.

gzip: stdout: Broken pipe
Traceback (most recent call last):
  File "image-extractor/image_extractor.py", line 641, in <module>
    extractor.process_data(data_file, args.max_events)
  File "image-extractor/image_extractor.py", line 273, in process_data
    random_tel_id = random.choice(selected_tels[tel_type])
  File "/home/kbruegge/.conda/envs/fact/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
Closing remaining open files:./test.h5...done
```

**Comment by bryankim96** [comment]
Sorry for the extremely late reply. This bug was due to inconsistencies in telescope type naming, which caused no telescopes to actually be read from the event_source. It has been fixed with e2b40f2770c5a424905b797a9a802ac6cd63b9a4.
